version: '3.9'

volumes:
  disk_data_protection_keys:
    name: disk_data_protection_keys
  idsrv_data_protection_keys:
    name: idsrv_data_protection_keys
  psql_db:
    name: psql_db
    external: false

networks:
  main_net:
    driver: bridge

services:
  psql_db:
    image: postgres:14.3
    container_name: psql_db
    ports:
      - "2345:5432"
    volumes:
      - psql_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "idsrv"
      POSTGRES_USER: "puser"
      POSTGRES_PASSWORD: "12qwasZX"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U puser -d idsrv" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - main_net
  tele_bot:
    container_name: tele_bot
    image: tele_bot:dev
    ports:
      - "127.0.0.1:8003:80"
    build:
      context: ${SERVICES}TelegramBot/TelegramBot.Api
      target: debug
    networks:
      - main_net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
      - BOT_TOKEN=${BOT_TOKEN}
      - WEB_HOOK_ENDPOINT=${WEB_HOOK_ENDPOINT}
  webapi:
    container_name: webapi
    image: webapi:dev
    build:
      context: ${SERVICES}Web/Web.Api
      target: debug
    ports:
      - "127.0.0.1:4432:443"
    networks:
      - main_net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/webapi.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/webapi.key
    volumes:
      - ./certs/webapi:/https/:ro
  disk:
    container_name: disk
    image: disk:dev
    build:
      context: ${SERVICES}Disk/Disk.Api
      target: debug
    ports:
      - "127.0.0.1:4431:443"
    networks:
      - main_net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/disk.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/disk.key
    volumes:
      - ./certs/disk/:/https/:ro
      - disk_data_protection_keys:/root/.aspnet/DataProtection-Keys:rw
  idsrv:
    container_name: idsrv
    image: idsrv:dev
    build:
      context: ${SERVICES}Identity/
      target: debug
    ports:
      - "127.0.0.1:4430:443"
    networks:
      - main_net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/idsrv.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/idsrv.key
    volumes:
      - ./certs/idsrv/:/https/:ro
      - idsrv_data_protection_keys:/root/.aspnet/DataProtection-Keys:rw
