version: '3.4'

# services:
# pgadmin:
#   container_name: pgadmin
#   image: dpage/pgadmin4:6.9
#   environment:
#     PGADMIN_DEFAULT_EMAIL: "mail@mail.ru"
#     PGADMIN_DEFAULT_PASSWORD: "12qwasZX"
#     PGADMIN_CONFIG_SERVER_MODE: "False"
#   volumes:
#     - pgadmin:/var/lib/pgadmin
#   ports:
#     - "5050:80"
#   restart: unless-stopped
#   deploy:
#     resources:
#       limits:
#         cpus: '0.5'
#         memory: 1G
#   networks:
#     - postgres
