version: '3.9'

networks:
  main:
    driver: bridge

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - main
  psql_db:
    image: postgres:14.5
    container_name: psql_db
    networks:
      - main
  disk:
    image: pachitko/disk:dev
    container_name: disk
    build:
      context: ./src
      dockerfile: Services/Disk/Disk.Api/Dockerfile
    networks:
      - main
  tele_bot:
    image: pachitko/tele_bot:dev
    container_name: tele_bot
    build:
      context: ./src
      dockerfile: Services/TelegramBot/TelegramBot.Api/Dockerfile
    networks:
      - main
  webapi:
    image: pachitko/webapi:dev
    container_name: webapi
    build:
      context: ./src
      dockerfile: Services/Web/Web.Api/Dockerfile
    networks:
      - main
  idsrv:
    image: pachitko/idsrv:dev
    container_name: idsrv
    build:
      context: ./src
      dockerfile: Services/Identity/Dockerfile
    networks:
      - main
  tempo_disk:
    image: pachitko/tempo_disk:dev
    container_name: tempo_disk
    build:
      context: ./src
      dockerfile: Services/TempoDisk/TempoDisk.Api/Dockerfile
    networks:
      - main
  gw:
    image: pachitko/gw:dev
    container_name: gw
    build: 
      context: ./src
      dockerfile: Gateway/Dockerfile
    networks:
      - main
    depends_on:
      - tempo_disk
  # schedule_parser:
  #   image: pachitko/schedule_parser:dev
  #   container_name: schedule_parser
  #   build:
  #     context: ./src
  #     dockerfile: Services/ScheduleParser/ScheduleParser.Api/Dockerfile